// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using QuartzNETDemoLibrary.Models;

namespace QuartzNETDemoConsoleApp
{
    public partial class DBContext1 : DbContext
    {
        public DBContext1()
        {
        }

        public DBContext1(DbContextOptions<DBContext1> options)
            : base(options)
        {
        }

        public virtual DbSet<SchedulerConfiguration> SchedulerConfiguration { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<SchedulerConfiguration>(entity =>
            {
                entity.HasNoKey();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}